// Code generated by protoc-gen-go.
// source: process.proto
// DO NOT EDIT!

/*
Package processUtility is a generated protocol buffer package.

It is generated from these files:
	process.proto

It has these top-level messages:
	Process
	ProcessSet
*/
package processUtility

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Process struct {
	ProcessID        *int32  `protobuf:"varint,1,opt,name=processID" json:"processID,omitempty"`
	VirtualSize      *int32  `protobuf:"varint,2,opt,name=virtualSize" json:"virtualSize,omitempty"`
	TimeStarted      *string `protobuf:"bytes,3,opt,name=timeStarted" json:"timeStarted,omitempty"`
	Command          *string `protobuf:"bytes,4,opt,name=command" json:"command,omitempty"`
	WasOpened        *bool   `protobuf:"varint,5,opt,name=wasOpened" json:"wasOpened,omitempty"`
	WasClosed        *bool   `protobuf:"varint,6,opt,name=wasClosed" json:"wasClosed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}

func (m *Process) GetProcessID() int32 {
	if m != nil && m.ProcessID != nil {
		return *m.ProcessID
	}
	return 0
}

func (m *Process) GetVirtualSize() int32 {
	if m != nil && m.VirtualSize != nil {
		return *m.VirtualSize
	}
	return 0
}

func (m *Process) GetTimeStarted() string {
	if m != nil && m.TimeStarted != nil {
		return *m.TimeStarted
	}
	return ""
}

func (m *Process) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *Process) GetWasOpened() bool {
	if m != nil && m.WasOpened != nil {
		return *m.WasOpened
	}
	return false
}

func (m *Process) GetWasClosed() bool {
	if m != nil && m.WasClosed != nil {
		return *m.WasClosed
	}
	return false
}

type ProcessSet struct {
	Processes        []*Process `protobuf:"bytes,1,rep,name=processes" json:"processes,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ProcessSet) Reset()         { *m = ProcessSet{} }
func (m *ProcessSet) String() string { return proto.CompactTextString(m) }
func (*ProcessSet) ProtoMessage()    {}

func (m *ProcessSet) GetProcesses() []*Process {
	if m != nil {
		return m.Processes
	}
	return nil
}

func init() {
}
